### ISSUE TITLE
include time zone info when writing to csv

### ISSUE THREAD

**Issue by bartaelterman** [inbo/bird-tracking-etl#5]

**Comment by stijnvanhoey** [comment]
The join is functioning and the ETL runs, but the resulting is not yet correct. 

The `tracking_ended_at` is not incorporated in the resulting file for `Roy` in the resulting file. As such, the join is also taking into account the dates outside the end date of the tracking:

index|ring_code|device_info_serial|tracking_started_at|tracking_ended_at|is_active|date_time
---|---|---|---|---|---|---
510496|L911116|5338|2016-05-20 18:00:00|||2016-05-21 13:55:18
510497|L911116|5338|2016-05-20 18:00:00|||2016-05-22 13:03:25
510498|L911116|5338|2016-05-20 18:00:00|||...
510499|L911116|5338|2016-05-20 18:00:00|||2016-07-09 00:00:00
510500|L911116|5338|2016-05-20 18:00:00|||2016-07-09 00:19:59
510500|L911116|5338|2016-05-20 18:00:00|||...

This should be checked:
- wrong procedure in the R-join
- file in the S3 bucket not up to date

**Comment by stijnvanhoey** [comment]
Just checked the S3-bucket and the metadata is not completely up to date, the `tracking_ended_at` has no entry for `Roy`.

**Comment by stijnvanhoey** [comment]
Implementation of the time-based join implemented, tested and also applied on the real data set, with the case of `Roy ` and `Fay`. The resulting tracks are linked with the `bird_name` (and `ring_code`,...) as follows:
![vega 2](https://cloud.githubusercontent.com/assets/754862/16869017/0a573b7e-4a7b-11e6-8ba7-3f35a323bf48.png)

This corresponds to the metadata tracker info. Plotting the coordinates of these two with different color scale:
![vega](https://cloud.githubusercontent.com/assets/754862/16868951/bc561670-4a7a-11e6-9d53-614f53e47a3f.png)
Shows the track logs are not joined with both of them, as required.

closing this issue...

(figs created with [altair](https://github.com/ellisonbg/altair))

**Comment by peterdesmet** [comment]
Putting that altair to good use. 👍

**Comment by bartaelterman** [comment]
So you guys noticed altair too... :-)
