### ISSUE TITLE
package incompatibility

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/bird-tracking-etl#8]
@bartaelterman Kan het zijn dat het die `lazy loading` is die nog voor problemen zorgt? Ik ken dat niet, wat doet dat precies?

Verder kan ik ook nog in de logs vinden: 
```
* installing *source* package ‘raster’ ...
```

De huidige install file die ik test ziet er als volgt uit:

```
raster_url <- "https://cran.r-project.org/src/contrib/Archive/raster/raster_2.4-18.tar.gz"
install.packages(raster_url, repos=NULL, type="source")

lubri_url <- "https://cran.r-project.org/src/contrib/lubridate_1.5.6.tar.gz"
install.packages(lubri_url, repos=NULL, type="source")

table_url <- "https://cran.r-project.org/src/contrib/data.table_1.9.6.tar.gz"
install.packages(table_url, repos=NULL, type="source")

geo_url <- "https://cran.r-project.org/src/contrib/Archive/geosphere/geosphere_1.3-13.tar.gz"
install.packages(geo_url, repos=NULL, type="source")

map_url <- "https://cran.r-project.org/src/contrib/Archive/maptools/maptools_0.8-36.tar.gz"
install.packages(map_url, repos=NULL, type="source")

sp_url <- "https://cran.r-project.org/src/contrib/Archive/sp/sp_1.1-1.tar.gz"
install.packages(sp_url, repos=NULL, type="source")

gdal_url <- "https://cran.r-project.org/src/contrib/Archive/rgdal/rgdal_1.1-9.tar.gz"
install.packages(gdal_url, repos=NULL, type="source")

install.packages("devtools", repos="http://cran.rstudio.com/")
library(devtools)
install_github("inbo/bird-tracking-etl")
```

**Comment by bartaelterman** [comment]
Die is blijkbaar nodig omdat ik ook data in het pakket heb gestoken. `LazyLoading` zorgt er dan voor dat die data pas wordt ingeladen wanneer het nodig is. Ik heb al op verschillende plaatsen gelezen dat data aan een pakket toevoegen zonder `Lazyloading=TRUE` een hele hoop andere problemen kan veroorzaken.

**Comment by bartaelterman** [comment]
we kunnen mss ook proberen `install_github` te vervangen door de repo te clonen en van lokale files te installeren. Misschien rijdt hij zich dan niet vast in de dependencies. Wild guess...

**Comment by bartaelterman** [comment]
of [dit](https://github.com/hadley/devtools/issues/863#issuecomment-137241474)...

**Comment by bartaelterman** [comment]
This should fix it:

https://github.com/inbo/bird-tracking-aws/commit/e5f5765835c69c6b55352d2d532ecb5f78979928
