### ISSUE TITLE
Merge data on tracking_range and device_info_serial. Use ring_code as bird identifier

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking-etl#9]
As noted in https://github.com/inbo/bird-tracking/issues/89, the `device_info_serial` is no longer valid as a unique bird identifier. We should use `ring_code` instead, which means we need that field for each tracking record.

In the preprocessing, merge metadata and data on `device_info_serial` AND have the data within the tracking range defined in the metadata. That should rule out double `device_info_serial`s.

**Comment by peterdesmet** [comment]
The fact that this will **remove test records** (records before `tracking_start_date`, usually at 18h) from the files we offer to users is ok for Eric Stienen (see email 2016-08-01). Those records were never included in the published DwC-A, so nothing changes there.

**Comment by peterdesmet** [comment]
I'm reopening this issue, as I don't think it has been tested yet. @stijnvanhoey?

**Comment by stijnvanhoey** [comment]
The join based on the combination of the `device-info-serial` and the start and end date has been implemented and [tests have been written](https://github.com/inbo/bird-tracking-etl/commit/ffeb867984dfea5751110c71c4ca7f1fcdd2583b) to check the behavior. It tests the join (check that period/device-info-serial combination is mapped to single bird) and the exclusion of data outside the date range.

As the resulting product of the join supports the usage of ring_code as bird identifier for the visualisation, I close this issue.
